spring.application.name=F1-database

spring.datasource.url=jdbc:mysql://localhost:${DB_PORT_MYSQL}/${DB_NAME_MYSQL}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER_MYSQL}
spring.datasource.password=${DB_PASSWORD_MYSQL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false